# 8.0 required to support Carthage
platform :ios, '8.0'

target "NUIDemo" do
  pod "NUIParse"
end

target "NUI" do
  pod "NUIParse"
end

target "NUITests" do
  pod 'FBSnapshotTestCase', '~> 1.6'
  pod 'UIImage+ColorFromImage', '0.0.2'
end
